# Generated by Django 3.2.5 on 2021-08-06 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210806_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SomeModel',
        ),
    ]
